/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
      "./src/**/*.{js,ts,jsx,tsx}",
      "./src/components/**/*.{js,ts,jsx,tsx}",
      "./src/modals/**/*.{js,ts,jsx,tsx}",
      "./src/modules/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
      extend: {
        fontFamily: {
          Manrope: "Manrope",
        },
        colors: {
          dew: "#eff9f1",
          info: "#0dcaf0",
          nero: "#282828",
          dark: "#212529",
          azure: "#edfeff",
          ghost: "#c7c7c8",
          linen: "#fff4e8",
          comet: "#626264",
          light: "#f8f9fa",
          quartz: "#ddddde",
          pippin: "#ffded5",
          jaguar: "#28282b",
          danger: "#dc3545",
          manatee: "#848485",
          success: "#198754",
          primary: "#c29901",
          dolphin: "#79797a",
          whisper: "#e9e9e9",
          warning: "#ffc107",
          magnolia: "#faf6ff",
          honeydew: "#f5fff6",
          seashell: "#fffaf6",
          cornsilk: "#fff8dd",
          ghost400: "#d2d2d3",
          greysuit: "#8e8e8f",
          mayablue: "#5ab3ff",
          comet400: "#5e5e60",
          solitude: "#e8ecef",
          darkgray: "#a8a8a8",
          alabaster: "#f9f5e6",
          gunpowder: "#4c4c4e",
          aliceblue: "#e9f5ff",
          whitemoke: "#f2f2f2",
          spunpearl: "#b1b1b2",
          secondary: "#ededed",
          radicalred: "#ec4d60",
          martinique: "#363538",
          scarpaflow: "#6e6d6f",
          scotchmist: "#f3ebcc",
          fruitsalad: "#3db34a",
          dodgerblue: "#1877f2",
          santasgrey: "#9a9a9c",
          whisper300: "#e5e5e5",
          whitemoke400:"#f4f4f4",
          whitemoke500:"#f8f8f8",
          reveiwsuccess:"#24B036", 
          spunpearl300: "#a5a5a7",
          alabaster300: "#faf7eb",
          aliceblue300: "#eff8ff",
          aliceblue400: "#f2f9ff",
          blackrussian: "#1f1f22",
          lavenderblush: "#fff9fd",
          darkpastelgreen: "#00b728",
          doublecolonialwhite: "#e7d699",
          lightGray:"#f4f4f4",
          dimGray:"#79797A",
          midGray:"#F8F8F8",
          semiMidGray:"#9A9A9C",
          deleteRed:"#E03137"
        },
        screens: {
          "3xl": { min: "99.125rem" },
          "desktop": "85.188rem",
          mdx1: { min: "850px", max: "1020px" },
          mdx2: { min: "768px", max: "1020px" },
          mdx3: { min: "640px", max: "991px" },
          xs: { max: "500px" },
          xs2: { max: "399px" },
          xs3: { min: "320px", max: "450px" },
        },
        lineHeight: {
          0: "0",
          87: 1.20,
          80: 1.18,
          48: 1.34,
          70: 1.17,
          50: 1.25,
          37:2.1
        },
      },
    },
    plugins: [ 
      require("@tailwindcss/line-clamp"),
      require("@tailwindcss/forms") 
    ],
  };